### ISSUE TITLE
win10 全局安装 mnpm-cli之后命令行执行mnpm报错 系统找不到指定的路径

### ISSUE THREAD

**Issue by xiaokk06** [springuper/mnpm#2]
全局安装命令： npm install -g mnpm-cli

**Comment by springuper** [comment]
你是美团员工？为什么在用 windows？

cli 使用 bash 写的，和 windows 不兼容。如果真的需要的话，欢迎贡献 PR，一个思路是使用 Node 脚本实现原来 bash 脚本的操作，这样可以借助 Node 的跨 OS 兼容性解决你的问题。

供参考：

- http://tstringer.github.io/npmjs/javascript/nodejs/2016/02/26/npm-global-packages.html
- http://stackoverflow.com/questions/25333570/npm-package-json-bin-wont-work-on-windows

**Comment by xiaokk06** [comment]
厦门这边开始用windows系统开发了，暂时通过修改.npmrc的registry解决这个问题了，之后有时间研究一下怎么解决这个问题吧
